export const ICONS = {
    "SUNNY" : "day-sunny",
    "CLOUDY" : "cloudy",
    "CLOUDY_GUSTS" : "cloudy-gusts",
    "CLOUDY_WINDY" : "cloudy-windy",
    "FOG" : "day-fog",
    "HAIL" : "hail",
    "HAZE" : "haze",
    "LIGHTNING" : "lightning",
    "RAIN" : "rain",
    "RAIN_MIX" : "rain-mix",
    "RAIN_WIND" : "rain-wind",
    "SHOWERS" : "showers",
    "SLEET" : "sleet",
    "SLEET_STORM" : "sleet-storm",
    "SNOW" : "snow",
    "SNOW_THUNDERSTORM" : "snow-thunderstorm",
    "SNOW_WIND" : "snow-wind",
    "SPRINKLE" : "sprinkle",
    "STORM_SHOWERS" : "storm-showers",
    "WINDY" : "windy",
    "SOLAR_ECLIPSE" : "solar-eclipse",
    "HOT" : "hot",
    "CLOUDY_HIGH" : "cloudy-high",
    "LIGHT_WIND" : "light-wind",
    "SUNNY_OVERCAST" : "day-sunny-overcast"
};
